import { PricingServiceKey } from "@/config/pricing.config";

export const SERVICE_ROUTE_MAP: Record<PricingServiceKey, string> = {
  abn: "/abn-registration",
  business_name: "/business-name-registration",
  family_trust: "/family-trust-setup",
  gst: "/gst-registration",
  charity: "/charity-setup",
  charity_ia: "/charity-setup",
  charity_clg: "/charity-setup",
  company: "/company-registration",
  smsf: "/smsf-setup",
  partnership: "/partnership-registration",
  unit_trust: "/unit-trust-setup",
  bare_trust: "/bare-trust-setup",
  individual_tax_return: "/individual-tax-return",
  sole_trader_tax_return: "/sole-trader-tax-return",
  bundle_tax_return: "/bundle-tax-return",
  tfn: "/tfn-registration",
  rental_properties: "/pricing?service=rental_properties",
  nfp_accounting: "/nfp-accounting",
  trust_accounting: "/trust-accounting-landing",
  company_accounting: "/company-accounting",
  asic_agent: "/asic-agent-services",
  smsf_accounting: "/smsf-accounting",
  partnership_tax: "/partnership-tax",
  bookkeeping: "/bookkeeping",
  payroll_services: "/payroll-services",
  business_plan: "/business-plan",
  business_valuation: "/business-valuation",
  business_due_diligence: "/business-due-diligence",
  business_wealth_structuring: "/business-wealth-structuring",
};
